### ISSUE TITLE
Add `liked` and `retweeted` flags to tweet object

### ISSUE THREAD

**Issue by myConsciousness** [twitterdev/open-evolution#16]
Hi amazing developers,

Twitter API v2.0 seems to have no way of knowing that a particular tweet has been liked or retweeted by an authenticated user. 

Due to the unavailability of this flag, the following UI expressions cannot be used in third-party apps when just using Twitter API v2.0.  

![スクリーンショット 2022-06-19 8 48 11](https://user-images.githubusercontent.com/13072231/174460422-92c7dd5f-10db-40b0-bc45-28a950dc141d.png)

**Comment by andypiper** [comment]
Thank you for raising this. I'm going to close this issue in favor of working via the Pull Request 👍🏻

**Comment by JohnRSim** [comment]
Ping.. Any movement on this now that @andypiper is no longer assigned on it?

Thanks.
