### ISSUE TITLE
Relation information between an authenticated user and the result of users/lookup

### ISSUE THREAD

**Issue by redouane59** [twitterdev/open-evolution#5]
It is really painful that when I use the [user lookup endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup), I can't know if the user is following me or not.
What do you think about adding two new fields in the API response, i.e : 

```
{
"followed": false,
"following": true
}
```

[Related Feedback](https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/42309286-add-friendship-expansion-to-retrieve-twitter-follo)

**Comment by andypiper** [comment]
Can you please re-submit your proposal using the [workflow described in the README](https://github.com/twitterdev/open-evolution#workflow)? Thank you. I'm going to close this issue.
