### ISSUE TITLE
User include in list of tweet

### ISSUE THREAD

**Issue by redouane59** [twitterdev/open-evolution#6]
This one is maybe hard to change but I face difficulties because we currently have this kind of data when calling an endpoint returning a list of tweet and asking for user information : 

``` 
  {
  data:[
        {
           // tweet 1
        },
        {
           // tweet 2
        }
     ],
  includes:{
        users:[
           {
              // user 1
           },
           {
              // user 2
           }
        ]
  }
```
As the user information is outside of the `Tweet` object, the mapping is not easy to do when deserializing it.

Better result would be something like : 

```
{
  data:[
  {
    // tweet 1
    // user 1
  },
  {
    // tweet 2
    // user 2
  }
}
```

Am I alone to face that ?

[Related feedback](https://twitterdevfeedback.uservoice.com/forums/922918-twitter-for-academic-research/suggestions/43492353-list-of-tweet-response-structure)

**Comment by andypiper** [comment]
Can you please re-submit your proposal using the [workflow described in the README](https://github.com/twitterdev/open-evolution#workflow)? Thank you. I'm going to close this issue.

**Comment by igorbrigadir** [comment]
For anyone else looking up how to do this, have a look at how twarc does it https://github.com/DocNow/twarc/blob/main/twarc/expansions.py#L106 

And you can run this in the command line with `twarc2 flatten` see twarc docs for usage.

or search tweets library https://github.com/twitterdev/search-tweets-python/blob/v2/searchtweets/result_stream.py#L239 

or TwitterAPI https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/TwitterAPI.py#L441 which is slightly different bit achieves the same goal

**Comment by redouane59** [comment]
> For anyone else looking up how to do this, have a look at how twarc does it https://github.com/DocNow/twarc/blob/main/twarc/expansions.py#L106
> 
> And you can run this in the command line with `twarc2 flatten` see twarc docs for usage.
> 
> or search tweets library https://github.com/twitterdev/search-tweets-python/blob/v2/searchtweets/result_stream.py#L239
> 
> or TwitterAPI https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/TwitterAPI.py#L441 which is slightly different bit achieves the same goal

Great idea, I'm going to check If I can do the same :)
